# Generated by Django 2.0.7 on 2018-07-10 00:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateField(auto_now_add=True)),
                ('copias', models.IntegerField()),
                ('nome', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('check', models.BooleanField()),
            ],
        ),
    ]
